// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $controlled_form from "./routes/controlled-form.tsx";
import * as $index from "./routes/index.tsx";
import * as $islands from "./routes/islands.tsx";
import * as $uncontrolled_form from "./routes/uncontrolled-form.tsx";
import * as $controlled_form_1 from "./islands/controlled-form.tsx";
import * as $test_island from "./islands/test-island.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/controlled-form.tsx": $controlled_form,
    "./routes/index.tsx": $index,
    "./routes/islands.tsx": $islands,
    "./routes/uncontrolled-form.tsx": $uncontrolled_form,
  },
  islands: {
    "./islands/controlled-form.tsx": $controlled_form_1,
    "./islands/test-island.tsx": $test_island,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
